### ISSUE TITLE
!version

### ISSUE THREAD

**Issue by dylanpiera** [dylanpiera/Mafia-Quickplay-DiscordBot#18]
Displays current version of the bot, useful to see what I trew into the cloud.

**Comment by DarthWolf13** [comment]
Also show version history

**Comment by dylanpiera** [comment]
As in the changes made between this version and the last when the command is ran @DarthWolf13 ?

**Comment by DarthWolf13** [comment]
List of all versions

**Comment by dylanpiera** [comment]
Since we don't want a huge log of messages being printed out with !version as it's only a debug command this will not be added.

Besides all versions can be found back right over here on github
https://github.com/dylanpiera/Mafia-Quickplay-DiscordBot/commits/master

**Comment by dylanpiera** [comment]
Possible solution for this #21

**Comment by dylanpiera** [comment]
Decided to go for the idea mentioned in #21
