### ISSUE TITLE
Bot playing

### ISSUE THREAD

**Issue by CheffOfGames** [dylanpiera/Mafia-Quickplay-DiscordBot#21]
Let the bot be playing "Mafia v"&currentVersion.

**Comment by dylanpiera** [comment]
Added since https://github.com/dylanpiera/Mafia-Quickplay-DiscordBot/commit/445c8c4ad70c589e43398b703b2cbd4ff856a105

**Comment by CheffOfGames** [comment]
Let the bot playing message say "Playing **as host in Mafia v1.0.0**" when a game has started.

**Comment by dylanpiera** [comment]
Not gonna keep changing the game, as it's a discord wide thing, and the bot is hosted across multiple servers.
