### ISSUE TITLE
Recognise edited posts

### ISSUE THREAD

**Issue by AussieEevee** [dylanpiera/Mafia-Quickplay-DiscordBot#29]
In Discord, it is possible to edit posts but it is generally frowned upon to edit your post, and usually against the rules.

The bot should be able to recognise if a post has been edited.

**Comment by CheffOfGames** [comment]
This has already been implemented in the bot: https://github.com/dylanpiera/Mafia-Quickplay-DiscordBot/commit/4658c1e37fd796ce6d67d4ed9b8d068e4f9c2ba4.
