### ISSUE TITLE
Role PM on Death change

### ISSUE THREAD

**Issue by DarthWolf13** [dylanpiera/Mafia-Quickplay-DiscordBot#32]
Change the layout for better reading

**Comment by AussieEevee** [comment]
You can bold things using ** on either side of what you want to bold.

https://support.discordapp.com/hc/en-us/articles/210298617-Markdown-Text-101-Chat-Formatting-Bold-Italic-Underline-

**Comment by dylanpiera** [comment]
Leave some suggestions, or perhaps a template of what a rolePM could look like, if you have an idea ;)

**Comment by dylanpiera** [comment]
Since no suggestions have been made in the mean time I'll close this until further notice.
