### ISSUE TITLE
Instant vote confirmation

### ISSUE THREAD

**Issue by AussieEevee** [dylanpiera/Mafia-Quickplay-DiscordBot#35]
I think the bot should give feedback when someone votes to let them know their vote has been registered.

**Comment by AussieEevee** [comment]
Is it possible for the bot to react to a vote, rather than just send a message?

**Comment by dylanpiera** [comment]
Not sure, I'll investigate that.

**Comment by AussieEevee** [comment]
Maybe if the bot sends the :ok_hand: reaction to let people know that the vote was received

**Comment by dylanpiera** [comment]
Bot sends a PM that you voted.
