### ISSUE TITLE
Cop scans do not appear to be working

### ISSUE THREAD

**Issue by AussieEevee** [dylanpiera/Mafia-Quickplay-DiscordBot#58]
![img_20170927_175145_034](https://user-images.githubusercontent.com/26673976/30913463-e2db8f58-a3c2-11e7-8619-21d6c8503b7f.jpg)

**Comment by dylanpiera** [comment]
Please note that the cop scan is working as intended, it is just not showing the target correctly. Will be fixed in next update 👍
