### ISSUE TITLE
Hyper Majority / SkipDay Vote / Lock Vote

### ISSUE THREAD

**Issue by dylanpiera** [dylanpiera/Mafia-Quickplay-DiscordBot#9]
what should be the case:

- Have a lock vote mechanic where the day would end when hyper majority of >50% is achieved with locked votes

- Have a Hyper Majority mechanic where after reaching hyper majority of (66%?) a 1 min timer would run till end of phase

- Skip day vote mechanic where if (66%?) vote this the day would end early

**Comment by DarthWolf13** [comment]
2nd
